using Xunit;
using Nd30.DocumentEngine.Parsing;
using Nd30.LegalValidator.Adapters;
using Nd30.LegalValidator.Catalog;
using Nd30.LegalValidator.Evaluation;
using Nd30.LegalValidator.Model;
using Nd30.SemanticDetector.Detection;

namespace Nd30.LegalValidator.Tests;

public sealed class LegalValidatorTests
{
    private static readonly string Root=FindRoot();
    private static readonly Lazy<RuleCatalog> CatalogCache=new(()=>RuleCatalog.LoadVerifiedRelease(Root));
    private static RuleCatalog Catalog()=>CatalogCache.Value;
    private static ValidationEngine Engine()=>new(Catalog());
    private static string FindRoot(){var d=new DirectoryInfo(AppContext.BaseDirectory);while(d is not null){if(File.Exists(Path.Combine(d.FullName,"release","admin-nd30-verified-rc-v20.yaml")))return d.FullName;d=d.Parent;}throw new DirectoryNotFoundException("legal root not found");}
    private static ValidationContext Base()=>new(){EvaluationDate=new DateOnly(2026,9,19)};
    private static ValidationResult One(string id,ValidationContext c)=>Assert.Single(Engine().Validate(c,[id]).Results);
    private static Nd30.LegalValidator.Model.EvidenceRecord Auth(string kind,string r="fixture")=>new(kind,EvidenceAuthority.Authoritative,r,1.0,false);

    [Fact] public void Verified_release_pack_is_exactly_435_verified_rules(){var c=Catalog();Assert.Equal(435,c.Rules.Count);Assert.All(c.Rules,r=>Assert.Equal("verified",r.Maturity));Assert.DoesNotContain(c.Rules,r=>r.Id=="ND30.PL1.I.II.5B.OFFICIAL_LETTER_NO_TYPE_HEADING");}
    [Fact] public void Missing_capability_is_not_evaluated(){var r=One("ND30.PL1.I.II.1A.NATIONAL_HEADER_TEXT",Base().Observe("semantic_component.national_header.text","CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM"));Assert.Equal(ValidationStatus.NOT_EVALUATED,r.Status);Assert.Contains("semantic_component_detection",r.MissingCapabilities);}
    [Fact] public void Applicability_false_is_not_applicable(){var c=Base().AddCapability("semantic_component_detection").SetField("document.type","official_letter").Observe("semantic_component.document_type_heading.uppercase",true);var r=One("ND30.PL1.I.II.5B.TYPE_UPPERCASE",c);Assert.Equal(ValidationStatus.NOT_APPLICABLE,r.Status);}
    [Fact] public void Applicability_unknown_is_not_evaluated(){var c=Base().AddCapability("semantic_component_detection").Observe("semantic_component.document_type_heading.uppercase",true);Assert.Equal(ValidationStatus.NOT_EVALUATED,One("ND30.PL1.I.II.5B.TYPE_UPPERCASE",c).Status);}
    [Fact] public void Equals_rule_passes_and_fails_definitively(){var c=Base().AddCapability("semantic_component_detection").Observe("semantic_component.national_header.text","CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM");Assert.Equal(ValidationStatus.PASS,One("ND30.PL1.I.II.1A.NATIONAL_HEADER_TEXT",c).Status);c.Observe("semantic_component.national_header.text","SAI");Assert.Equal(ValidationStatus.FAIL,One("ND30.PL1.I.II.1A.NATIONAL_HEADER_TEXT",c).Status);}
    [Fact] public void Numeric_range_rule_passes_and_fails(){var c=Base().AddCapability("semantic_component_detection","effective_run_style").Observe("semantic_component.national_header.font_size_pt",13d);Assert.Equal(ValidationStatus.PASS,One("ND30.PL1.I.II.1A.NATIONAL_HEADER_SIZE",c).Status);c.Observe("semantic_component.national_header.font_size_pt",15d);Assert.Equal(ValidationStatus.FAIL,One("ND30.PL1.I.II.1A.NATIONAL_HEADER_SIZE",c).Status);}
    [Fact] public void Regex_rule_is_evaluated(){var c=Base().AddCapability("semantic_component_detection").Observe("semantic_component.document_number.text","09");Assert.Equal(ValidationStatus.PASS,One("ND30.PL1.I.II.3C.NUMBER_LEADING_ZERO_LT10",c).Status);c.Observe("semantic_component.document_number.text","9");Assert.Equal(ValidationStatus.FAIL,One("ND30.PL1.I.II.3C.NUMBER_LEADING_ZERO_LT10",c).Status);}
    [Fact] public void Semantic_uncertainty_requires_review(){var c=Base().AddCapability("semantic_component_detection").Observe("semantic_component.national_header.text","CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM").MarkUncertain("semantic_component.national_header.text");Assert.Equal(ValidationStatus.NEEDS_REVIEW,One("ND30.PL1.I.II.1A.NATIONAL_HEADER_TEXT",c).Status);}
    [Fact] public void Workflow_rule_rejects_docx_metadata_as_authoritative_evidence(){var key="workflow.events";var c=Base().AddCapability("workflow_event_log").Observe(key,new[]{"assign_number_and_issue_time","register_outgoing","finalize_paper_or_organization_sign_electronic","issue_and_track","retain_outgoing"},new("docx_modified_time",EvidenceAuthority.Derived,"docProps/core.xml"));Assert.Equal(ValidationStatus.NOT_EVALUATED,One("ND30.ART14.OUTGOING_WORKFLOW_ORDER",c).Status);c.Observe(key,c.ObservedValues[key],Auth("workflow_event_log"));Assert.Equal(ValidationStatus.PASS,One("ND30.ART14.OUTGOING_WORKFLOW_ORDER",c).Status);}
    [Fact] public void Workflow_order_failure_is_definitive_with_authoritative_log(){var c=Base().AddCapability("workflow_event_log").Observe("workflow.events",new[]{"register_outgoing","assign_number_and_issue_time"},Auth("workflow_event_log"));Assert.Equal(ValidationStatus.FAIL,One("ND30.ART14.OUTGOING_WORKFLOW_ORDER",c).Status);}
    [Fact] public void System_capability_is_not_inferred_from_docx(){var id="ND30.PL6.I.II.AUTHENTICITY_RELIABILITY_INTEGRITY_ACCESS";var rule=Catalog().Rules.Single(x=>x.Id==id);var c=Base().AddCapability("system_capability_audit").Observe(rule.Target.Key,new[]{"authenticity","reliability","integrity","authorized_access"},new("docx_features",EvidenceAuthority.Derived,"document.xml"));Assert.Equal(ValidationStatus.NOT_EVALUATED,One(id,c).Status);c.Observe(rule.Target.Key,c.ObservedValues[rule.Target.Key],Auth("system_capability_audit","system-audit.json"));Assert.Equal(ValidationStatus.PASS,One(id,c).Status);}
    [Fact] public void Reference_rule_is_not_evaluated_until_overlay_resolves(){var c=Base().AddCapability("security_policy_resolver").SetField("security.classification","state_secret").Observe("copy_context.security_overlay",true);Assert.Equal(ValidationStatus.NOT_EVALUATED,One("ND30.ART27.P2.SECRET_MATERIAL_COPYING_DELEGATES_TO_SECRECY_LAW",c).Status);c.ReferenceResults["current_secrecy_law"]=true;Assert.Equal(ValidationStatus.PASS,One("ND30.ART27.P2.SECRET_MATERIAL_COPYING_DELEGATES_TO_SECRECY_LAW",c).Status);}
    [Fact] public void Required_fields_and_all_of_and_required_effects_work(){var cat=Catalog();var rf=cat.Rules.First(x=>Convert.ToString(x.Constraint["type"])=="required_fields");var c=Base().AddCapability(rf.RequiresCapabilities.ToArray()).Observe(rf.Target.Key,new Dictionary<string,object?>());if(rf.RequiresCapabilities.Contains("workflow_event_log"))c.Observe(rf.Target.Key,c.ObservedValues[rf.Target.Key],Auth("workflow_event_log"));Assert.Equal(ValidationStatus.FAIL,One(rf.Id,c).Status);}
    [Fact] public void Deadline_requires_real_working_day_calendar(){var c=Base().AddCapability("workflow_event_log","working_day_calendar","timezone_context").SetField("authorized_signer_signed_at","2026-09-18T10:00:00+07:00").Observe("workflow.number_assigned_at","2026-09-21T09:00:00+07:00",Auth("workflow_event_log"));Assert.Equal(ValidationStatus.NOT_EVALUATED,One("ND30.ART15.P2.PAPER_NUMBER_DEADLINE_NEXT_WORKDAY",c).Status);c.WorkingDayCalendar=new WeekendCalendar();Assert.Equal(ValidationStatus.PASS,One("ND30.ART15.P2.PAPER_NUMBER_DEADLINE_NEXT_WORKDAY",c).Status);}
    [Fact] public void Coverage_contract_prevents_false_full_compliance(){var c=Base().AddCapability("semantic_component_detection").Observe("semantic_component.national_header.text","CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM");var report=Engine().Validate(c,["ND30.PL1.I.II.1A.NATIONAL_HEADER_TEXT","ND30.PL1.I.II.1A.NATIONAL_HEADER_SIZE"]);Assert.False(report.FullComplianceClaimAllowed);Assert.True(report.EvaluatedCoveragePercent<100);Assert.Contains("cannot be claimed",report.ComplianceStatement);}
    [Fact] public void Signed_or_audit_only_document_blocks_patch_eligibility(){var c=Base().AddCapability("semantic_component_detection","effective_run_style").Observe("semantic_component.national_header.bold",false);c.DocumentPatchPolicy=Nd30.DocumentEngine.Model.PatchPolicy.AUDIT_ONLY;var r=One("ND30.PL1.I.II.1A.NATIONAL_HEADER_BOLD",c);Assert.Equal(ValidationStatus.FAIL,r.Status);Assert.Equal(PatchEligibility.PROHIBITED,r.PatchEligibility);}
    [Fact] public void Semantic_adapter_drives_real_docx_text_rule_without_false_global_compliance(){var f=Path.Combine(Root,"fixtures","v23","02-named-decision.docx");var parsed=new DocxParser().Parse(f);Assert.NotNull(parsed.Document);var sem=new AdministrativeSemanticDetector().Detect(parsed.Document!);var c=SemanticValidationContextBuilder.Build(parsed.Document!,sem,new DateOnly(2026,9,19));var report=Engine().Validate(c,["ND30.PL1.I.II.1A.NATIONAL_HEADER_TEXT","ND30.PL1.I.II.1B.MOTTO_TEXT"]);Assert.Equal(2,report.PassCount);Assert.True(report.FullComplianceClaimAllowed);}
    [Fact] public void Full_verified_pack_never_claims_compliance_from_docx_only(){var f=Path.Combine(Root,"fixtures","v23","02-named-decision.docx");var parsed=new DocxParser().Parse(f);var sem=new AdministrativeSemanticDetector().Detect(parsed.Document!);var report=Engine().Validate(SemanticValidationContextBuilder.Build(parsed.Document!,sem,new DateOnly(2026,9,19)));Assert.False(report.FullComplianceClaimAllowed);Assert.True(report.NotEvaluatedCount>0);Assert.Equal(435,report.Results.Count);}

    private sealed class WeekendCalendar:IWorkingDayCalendar{public DateOnly NextWorkingDay(DateOnly date){var d=date.AddDays(1);while(d.DayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday)d=d.AddDays(1);return d;}}
}
