using Xunit;
using Nd30.LegalValidator.Evaluation;
using Nd30.LegalValidator.Model;
namespace Nd30.LegalValidator.Tests;
public sealed class V25L2HardeningTests {
 private static RuleDefinition Rule(IReadOnlyDictionary<string,object?>? applicability=null,string capability="cap")=>new("TEST.RULE","administrative","document_format","verified",new RuleSource("VN-STATE-ND30-2020","test"),new DateOnly(2020,3,5),null,new RuleTarget("semantic_component","test","value"),new Dictionary<string,object?>{{"type","equals"},{"value","ok"}},applicability,"LEGAL_ERROR","PROHIBITED",[capability]);
 private static EvidenceRecord Auth()=>new("semantic_component_detection",EvidenceAuthority.Authoritative,"fixture",1.0,false);
 [Fact] public void Missing_required_capability_is_not_evaluated_not_pass(){var r=new RuleEvaluator().Evaluate(Rule(),new ValidationContext{EvaluationDate=new(2026,9,21)});Assert.Equal(ValidationStatus.NOT_EVALUATED,r.Status);Assert.Contains("cap",r.MissingCapabilities);}
 [Fact] public void Missing_observation_is_not_evaluated_not_pass(){var c=new ValidationContext{EvaluationDate=new(2026,9,21)};c.AddCapability("cap");Assert.Equal(ValidationStatus.NOT_EVALUATED,new RuleEvaluator().Evaluate(Rule(),c).Status);}
 [Fact] public void Unsupported_applicability_operator_is_not_evaluated(){var a=new Dictionary<string,object?>{{"all",new object?[]{new Dictionary<string,object?>{{"field","document.type"},{"operator","future_operator"},{"value","decision"}}}}};var c=new ValidationContext{EvaluationDate=new(2026,9,21)};c.SetField("document.type","decision").AddCapability("cap").Observe("semantic_component.test.value","ok",Auth());var r=new RuleEvaluator().Evaluate(Rule(a),c);Assert.Equal(ValidationStatus.NOT_EVALUATED,r.Status);Assert.Contains("unsupported",r.Reason,StringComparison.OrdinalIgnoreCase);}
 [Fact] public void Non_applicable_rule_is_not_fail(){var a=new Dictionary<string,object?>{{"all",new object?[]{new Dictionary<string,object?>{{"field","document.type"},{"operator","equals"},{"value","decision"}}}}};var c=new ValidationContext{EvaluationDate=new(2026,9,21)};c.SetField("document.type","official_letter").AddCapability("cap").Observe("semantic_component.test.value","bad",Auth());Assert.Equal(ValidationStatus.NOT_APPLICABLE,new RuleEvaluator().Evaluate(Rule(a),c).Status);}
 [Fact] public void Temporally_inactive_rule_is_not_active(){var r=Rule() with {EffectiveTo=new DateOnly(2025,12,31)};var c=new ValidationContext{EvaluationDate=new(2026,9,21)};c.AddCapability("cap").Observe(r.Target.Key,"bad",Auth());Assert.Equal(ValidationStatus.NOT_APPLICABLE,new RuleEvaluator().Evaluate(r,c).Status);}
 [Fact] public void Evaluator_exception_is_isolated_as_not_evaluated(){var r=Rule() with {Constraint=new Dictionary<string,object?>{{"type","regex"},{"pattern","["}}};var c=new ValidationContext{EvaluationDate=new(2026,9,21)};c.AddCapability("cap").Observe(r.Target.Key,"x",Auth());var x=new RuleEvaluator().Evaluate(r,c);Assert.Equal(ValidationStatus.NOT_EVALUATED,x.Status);Assert.Contains("evaluation error",x.Reason,StringComparison.OrdinalIgnoreCase);}
 [Fact] public void Evidence_provenance_is_preserved(){var r=Rule();var c=new ValidationContext{EvaluationDate=new(2026,9,21)};c.AddCapability("cap").Observe(r.Target.Key,"ok",Auth());var x=new RuleEvaluator().Evaluate(r,c);Assert.Equal(ValidationStatus.PASS,x.Status);Assert.Single(x.Evidence);Assert.Equal("fixture",x.Evidence[0].Reference);Assert.Equal(r.Id,x.RuleId);Assert.Equal(r.Source,x.Source);}
}
