using Xunit;using DocumentFormat.OpenXml.Packaging;using W=DocumentFormat.OpenXml.Wordprocessing;using Nd30.DocumentEngine.Model;using Nd30.LegalValidator.Authorization;using Nd30.LegalValidator.Execution;using Nd30.LegalValidator.Model;using Nd30.LegalValidator.Remediation;using Nd30.LegalValidator.State;
namespace Nd30.LegalValidator.Tests;
public sealed class V26FinalAuthorityRevalidationTests{
 static DocumentIdentity D(string p)=>DocumentIdentityService.FromFile(p);static RuleIdentity R(string id="RULE.1")=>new(id,"SRC","loc");static PackageSafetyState S()=>new(true,false,false,false,false,false,false,[],PatchPolicy.NORMAL,[]);static ValidationResult F(string rule="RULE.1")=>new(rule,ValidationStatus.FAIL,"LEGAL_ERROR",new("SRC","loc"),new("paragraph","title","alignment"),"x","y",[new("semantic_component_detection",EvidenceAuthority.Authoritative,"ev",1,false,new Dictionary<string,string>{{"target_id","p1"}})],[],[],"applicable",1,PatchEligibility.ELIGIBLE,"test");static RemediationProposal P(DocumentIdentity d,string rule="RULE.1")=>new RemediationPlanner().Propose(F(rule),S(),"format",new(d,R(rule)));
 static string Doc(string dir){var p=Path.Combine(dir,"in.docx");using var d=WordprocessingDocument.Create(p,DocumentFormat.OpenXml.WordprocessingDocumentType.Document);var m=d.AddMainDocumentPart();m.Document=new W.Document(new W.Body(new W.Paragraph(new W.ParagraphProperties(new W.Justification{Val=W.JustificationValues.Left}),new W.Run(new W.Text("CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM"))),new W.Paragraph(new W.ParagraphProperties(new W.SpacingBetweenLines{After="0"}),new W.Run(new W.Text("Độc lập - Tự do - Hạnh phúc")))));m.Document.Save();return p;}
 static AuthorizedMutationRequest Align(string path){var d=D(path);var p=P(d);var target=new ParagraphTargetLocator("/word/document.xml","paragraph","p1","body/p[1]",Nd30.LegalValidator.Mutation.ParagraphAlignmentMutationExecutor.Anchor("CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM"),"paragraph.alignment");var i=MutationIntent.Create(p,target,ParagraphAlignmentValue.LEFT,ParagraphAlignmentValue.CENTER);var a=AuthorizationArtifact.Issue(p,i);return AuthorizationBoundary.Authorize(p,S(),a,d,R(),i).Request!;}
 static AuthorizedMutationRequest Space(string path,string after="120"){var d=D(path);var p=P(d,"RULE.2");var i=V26FormattingIntent.ParagraphSpacingAfter(p,"body/p[2]","0",after);var a=new AuthorizationArtifact(new string('a',24),p.ProposalId,p.StateBinding!,"single-exact-mutation-intent",null,i.MutationIntentId);return AuthorizationBoundary.Authorize(p,S(),a,d,R("RULE.2"),i).Request!;}
 [Fact]public void Valid_authorized_requests_build_deterministic_plan(){using var t=new TD();var s=Doc(t.P);var a=Align(s);var b=Space(s);Assert.Equal(MutationPlan.Create([a,b]).PlanId,MutationPlan.Create([b,a]).PlanId);}
 [Fact]public void Forged_authorization_string_cannot_create_plan(){Assert.DoesNotContain(typeof(MutationPlan).GetMethods(),m=>m.Name=="Create"&&m.GetParameters().Any(p=>p.ParameterType==typeof(string)));}
 [Fact]public void Raw_plan_operation_is_not_public(){Assert.False(Type.GetType("Nd30.LegalValidator.Execution.PlanOperation, LegalValidator")!.IsPublic);}
 [Fact]public void Changed_target_is_rejected(){using var t=new TD();var s=Doc(t.P);var q=Space(s);var forged=q with{V26Intent=q.V26Intent! with{TargetPath="body/p[1]"}};Assert.Throws<ArgumentException>(()=>MutationPlan.Create([forged]));}
 [Fact]public void Changed_expected_before_is_rejected(){using var t=new TD();var s=Doc(t.P);var q=Space(s);var forged=q with{V26Intent=q.V26Intent! with{ExpectedBefore="9"}};Assert.Throws<ArgumentException>(()=>MutationPlan.Create([forged]));}
 [Fact]public void Changed_desired_after_is_rejected(){using var t=new TD();var s=Doc(t.P);var q=Space(s);var forged=q with{V26Intent=q.V26Intent! with{DesiredAfter="240"}};Assert.Throws<ArgumentException>(()=>MutationPlan.Create([forged]));}
 [Fact]public void Mixed_document_state_is_rejected(){using var t=new TD();var a=Doc(t.P);var b=Path.Combine(t.P,"b.docx");File.Copy(a,b);using(var d=WordprocessingDocument.Open(b,true)){d.MainDocumentPart!.Document.Body!.Append(new W.Paragraph(new W.Run(new W.Text("x"))));d.MainDocumentPart.Document.Save();}Assert.Throws<ArgumentException>(()=>MutationPlan.Create([Align(a),Align(b)]));}
 [Fact]public void Conflict_semantics_preserved(){using var t=new TD();var s=Doc(t.P);var a=Space(s,"120");var b=Space(s,"240");var p=MutationPlan.Create([a,b]);Assert.True(p.HasConflict);Assert.Contains(ConflictClass.CONFLICTING,p.Classifications);}
 [Fact]public void Canonical_revalidator_executes_real_parser_detector_and_435_rule_validator(){var root=FindRoot();var f=Path.Combine(root,"fixtures","v23","02-named-decision.docx");var r=new CanonicalDocumentRevalidator(root,new(2026,9,19)).Revalidate(f);Assert.True(r.Completed);Assert.Equal(435,r.Results.Count);Assert.NotEmpty(r.RemainingFindings);}
 [Fact]public void Successful_atomic_execution_uses_canonical_revalidator_and_promotes(){using var t=new TD();var s=Doc(t.P);var root=FindRoot();var o=Path.Combine(t.P,"out.docx");using var j=new FileExecutionJournal(Path.Combine(t.P,"j"));var x=new AtomicMutationPlanExecutor(j,new CanonicalDocumentRevalidator(root,new(2026,9,19))).Execute(s,o,MutationPlan.Create([Align(s),Space(s)]),"req","key");Assert.True(x.Success);Assert.True(File.Exists(o));Assert.True(x.Revalidation!.Completed);Assert.Equal(435,x.Revalidation.Results.Count);Assert.Equal(D(s).Digest,x.InputIdentity.Digest);}
 [Fact]public void Fatal_revalidation_prevents_publication(){using var t=new TD();var s=Doc(t.P);var o=Path.Combine(t.P,"out.docx");using var j=new FileExecutionJournal(Path.Combine(t.P,"j"));var x=new AtomicMutationPlanExecutor(j,new FailRV()).Execute(s,o,MutationPlan.Create([Align(s)]),"req","key");Assert.Equal(PlanExecutionOutcome.REVALIDATION_FAILED,x.Outcome);Assert.False(File.Exists(o));Assert.Equal(D(s).Digest,x.InputIdentity.Digest);}
 static string FindRoot(){var d=new DirectoryInfo(AppContext.BaseDirectory);while(d is not null){if(File.Exists(Path.Combine(d.FullName,"release","admin-nd30-verified-rc-v20.yaml")))return d.FullName;d=d.Parent;}throw new DirectoryNotFoundException();}sealed class FailRV:IDocumentRevalidator{public CanonicalRevalidationResult Revalidate(string p)=>new(false,false,false,[],[],[],"fatal");}sealed class TD:IDisposable{public string P{get;}=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));public TD()=>Directory.CreateDirectory(P);public void Dispose(){try{Directory.Delete(P,true);}catch{}}}
}
