#!/usr/bin/env python3
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'v22-runtime/tests/LegalValidator.Tests/V26PreservedExecutionSafetyTests.cs'
p.write_text(r'''using Xunit;using Nd30.LegalValidator.Execution;using Nd30.LegalValidator.Authorization;using Nd30.LegalValidator.Remediation;using Nd30.LegalValidator.State;using Nd30.LegalValidator.Model;using Nd30.DocumentEngine.Model;using DocumentFormat.OpenXml.Packaging;using W=DocumentFormat.OpenXml.Wordprocessing;namespace Nd30.LegalValidator.Tests;public sealed class V26FinalAuthorityRevalidationTestsPreservedExecutionSafety{
static string Doc(string d){var p=Path.Combine(d,"i.docx");using var x=WordprocessingDocument.Create(p,DocumentFormat.OpenXml.WordprocessingDocumentType.Document);var m=x.AddMainDocumentPart();m.Document=new W.Document(new W.Body(new W.Paragraph(new W.ParagraphProperties(new W.Justification{Val=W.JustificationValues.Left}),new W.Run(new W.Text("CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM")))));m.Document.Save();return p;}static AuthorizedMutationRequest Q(string p){var d=DocumentIdentityService.FromFile(p);var r=new RuleIdentity("R","S","L");var f=new ValidationResult("R",ValidationStatus.FAIL,"LEGAL_ERROR",new("S","L"),new("paragraph","title","alignment"),"x","y",[new("semantic_component_detection",EvidenceAuthority.Authoritative,"e",1,false,new Dictionary<string,string>{{"target_id","p1"}})],[],[],"applicable",1,PatchEligibility.ELIGIBLE,"t");var s=new PackageSafetyState(true,false,false,false,false,false,false,[],PatchPolicy.NORMAL,[]);var pr=new RemediationPlanner().Propose(f,s,"format",new(d,r));var t=new ParagraphTargetLocator("/word/document.xml","paragraph","p1","body/p[1]",Nd30.LegalValidator.Mutation.ParagraphAlignmentMutationExecutor.Anchor("CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM"),"paragraph.alignment");var i=MutationIntent.Create(pr,t,ParagraphAlignmentValue.LEFT,ParagraphAlignmentValue.CENTER);return AuthorizationBoundary.Authorize(pr,s,AuthorizationArtifact.Issue(pr,i),d,r,i).Request!;}
[Fact]public void Journal_same_key_same_semantics_recovers_success(){using var t=new T();var s=Doc(t.P);var p=MutationPlan.Create([Q(s)]);using var j=new FileExecutionJournal(t.P);var a=j.Begin("k",p,"r",p.InputDocumentDigest);j.Succeed(a.Record!.ExecutionId,"out","o");Assert.Equal(JournalDecision.ALREADY_EXECUTED,j.Begin("k",p,"r",p.InputDocumentDigest).Decision);}
[Fact]public void Journal_same_key_different_semantics_conflicts(){using var t=new T();var s=Doc(t.P);var p=MutationPlan.Create([Q(s)]);using var j=new FileExecutionJournal(t.P);j.Begin("k",p,"r",p.InputDocumentDigest);Assert.Equal(JournalDecision.IDEMPOTENCY_CONFLICT,j.Begin("k",p,"different",p.InputDocumentDigest).Decision);}
[Fact]public void Successful_execution_is_durable_across_reopen(){using var t=new T();var s=Doc(t.P);var p=MutationPlan.Create([Q(s)]);string id;using(var j=new FileExecutionJournal(t.P)){var a=j.Begin("k",p,"r",p.InputDocumentDigest);id=a.Record!.ExecutionId;j.Succeed(id,"digest","out");}using(var j=new FileExecutionJournal(t.P)){Assert.Equal(ExecutionStatus.SUCCEEDED,j.Get(id)!.Status);Assert.Equal("digest",j.Get(id)!.OutputDigest);}}
[Fact]public void Failed_execution_is_not_silently_rerun(){using var t=new T();var s=Doc(t.P);var p=MutationPlan.Create([Q(s)]);using var j=new FileExecutionJournal(t.P);var a=j.Begin("k",p,"r",p.InputDocumentDigest);j.Fail(a.Record!.ExecutionId,"x");Assert.Equal(JournalDecision.PREVIOUS_FAILED,j.Begin("k",p,"r",p.InputDocumentDigest).Decision);}
[Fact]public void Journal_corruption_fails_closed(){using var t=new T();File.WriteAllText(Path.Combine(t.P,"journal.json"),"{");using var j=new FileExecutionJournal(t.P);Assert.Throws<JournalException>(()=>j.Get("x"));}
[Fact]public void Duplicate_authorized_request_is_deterministic(){using var t=new T();var s=Doc(t.P);var q=Q(s);var p=MutationPlan.Create([q,q]);Assert.Contains(ConflictClass.DUPLICATE,p.Classifications);Assert.False(p.HasConflict);Assert.Single(p.Operations);}
sealed class T:IDisposable{public string P{get;}=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));public T()=>Directory.CreateDirectory(P);public void Dispose(){try{Directory.Delete(P,true);}catch{}}}}
''')
print('V26 preserved execution safety tests materialized')
