#!/usr/bin/env python3
from pathlib import Path
import argparse
ROOT=Path(__file__).resolve().parents[1]
TEST=ROOT/'v22-runtime/tests/LegalValidator.Tests/V26ProductionSafeAutofixTests.cs'
PROD=ROOT/'v22-runtime/src/LegalValidator/Execution/V26ExecutionSafety.cs'
p=argparse.ArgumentParser();p.add_argument('--tests-only',action='store_true');p.add_argument('--production-only',action='store_true');a=p.parse_args()
if not a.production_only:
 TEST.parent.mkdir(parents=True,exist_ok=True)
 TEST.write_text(r'''using Xunit;using Nd30.DocumentEngine.Model;using Nd30.LegalValidator.Execution;namespace Nd30.LegalValidator.Tests;
public sealed class V26ProductionSafeAutofixTests{
 static PlanOperation A(string after="CENTER")=>new("intent-a","RULE.1","finding-a","/word/document.xml","body/p[1]","paragraph.alignment","DIRECT","LEFT",after);
 static PlanOperation S()=>new("intent-s","RULE.2","finding-s","/word/document.xml","body/p[2]","paragraph.spacing.after","DIRECT","0","120");
 [Fact]public void Plan_identity_is_deterministic(){Assert.Equal(MutationPlan.Create("doc", "auth",[S(),A()]).PlanId,MutationPlan.Create("doc","auth",[A(),S()]).PlanId);}
 [Fact]public void Semantic_change_changes_plan_identity(){Assert.NotEqual(MutationPlan.Create("doc","auth",[A()]).PlanId,MutationPlan.Create("doc","auth",[A("RIGHT")]).PlanId);}
 [Fact]public void Independent_operations_are_accepted(){var p=MutationPlan.Create("doc","auth",[A(),S()]);Assert.False(p.HasConflict);Assert.Equal(2,p.Operations.Count);}
 [Fact]public void Exact_duplicates_are_deduplicated(){var p=MutationPlan.Create("doc","auth",[A(),A()]);Assert.False(p.HasConflict);Assert.Single(p.Operations);Assert.Equal(ConflictClass.DUPLICATE,p.Classifications.Single());}
 [Fact]public void Different_desired_state_on_same_target_property_conflicts(){var p=MutationPlan.Create("doc","auth",[A(),A("RIGHT")]);Assert.True(p.HasConflict);Assert.Contains(ConflictClass.CONFLICTING,p.Classifications);}
 [Fact]public void Unsupported_property_fails_closed(){Assert.Throws<ArgumentException>(()=>MutationPlan.Create("doc","auth",[A() with{Property="xml.xpath"}]));}
 [Fact]public void Journal_same_key_same_semantics_recovers_success(){using var d=new TempDir();var j=new FileExecutionJournal(d.Path);var p=MutationPlan.Create("doc","auth",[A()]);var b=j.Begin("key",p,"req","input");Assert.Equal(JournalDecision.STARTED,b.Decision);j.Succeed(b.Record!.ExecutionId,"out","/x");var r=new FileExecutionJournal(d.Path).Begin("key",p,"req","input");Assert.Equal(JournalDecision.ALREADY_EXECUTED,r.Decision);Assert.Equal(ExecutionStatus.SUCCEEDED,r.Record!.Status);}
 [Fact]public void Journal_same_key_different_semantics_conflicts(){using var d=new TempDir();var j=new FileExecutionJournal(d.Path);j.Begin("key",MutationPlan.Create("doc","auth",[A()]),"req","input");var x=j.Begin("key",MutationPlan.Create("doc","auth",[S()]),"req","input");Assert.Equal(JournalDecision.IDEMPOTENCY_CONFLICT,x.Decision);}
 [Fact]public void Failed_execution_is_not_silently_rerun(){using var d=new TempDir();var j=new FileExecutionJournal(d.Path);var p=MutationPlan.Create("doc","auth",[A()]);var b=j.Begin("key",p,"req","input");j.Fail(b.Record!.ExecutionId,"WRITE_FAILED");Assert.Equal(JournalDecision.PREVIOUS_FAILED,j.Begin("key",p,"req","input").Decision);}
 [Fact]public void Journal_corruption_fails_closed(){using var d=new TempDir();System.IO.File.WriteAllText(System.IO.Path.Combine(d.Path,"journal.json"),"{");Assert.Throws<JournalException>(()=>new FileExecutionJournal(d.Path).Begin("k",MutationPlan.Create("d","a",[A()]),"r","i"));}
 [Fact]public void Audit_record_binds_required_authority(){using var d=new TempDir();var j=new FileExecutionJournal(d.Path);var p=MutationPlan.Create("doc","auth",[A(),S()]);var b=j.Begin("key",p,"request-1","inputhash");j.Succeed(b.Record!.ExecutionId,"outputhash","/out.docx");var r=j.Get(b.Record.ExecutionId)!;Assert.Equal(p.PlanId,r.PlanId);Assert.Equal("request-1",r.RequestId);Assert.Equal("inputhash",r.InputDigest);Assert.Equal("outputhash",r.OutputDigest);Assert.Equal(2,r.Operations.Count);}
 sealed class TempDir:IDisposable{public string Path{get;}=System.IO.Path.Combine(System.IO.Path.GetTempPath(),Guid.NewGuid().ToString("N"));public TempDir()=>Directory.CreateDirectory(Path);public void Dispose(){try{Directory.Delete(Path,true);}catch{}}}
}''',encoding='utf-8')
if not a.tests_only:
 PROD.parent.mkdir(parents=True,exist_ok=True)
 PROD.write_text(r'''using System.Security.Cryptography;using System.Text;using System.Text.Json;using System.Text.RegularExpressions;
namespace Nd30.LegalValidator.Execution;
public enum ConflictClass{INDEPENDENT,DUPLICATE,CONFLICTING,UNSUPPORTED_UNRESOLVABLE}
public sealed record PlanOperation(string MutationIntentId,string RuleId,string FindingReference,string PartUri,string TargetPath,string Property,string Provenance,string ExpectedBefore,string DesiredAfter){public string SemanticKey=>string.Join("|",PartUri,TargetPath,Property,Provenance,ExpectedBefore,DesiredAfter,RuleId,FindingReference,MutationIntentId);public string TargetProperty=>string.Join("|",PartUri,TargetPath,Property);}
public sealed record MutationPlan(string PlanId,string InputDocumentDigest,string AuthorizationIdentity,IReadOnlyList<PlanOperation> Operations,IReadOnlyList<ConflictClass> Classifications,bool HasConflict){
 static readonly HashSet<string> Supported=["paragraph.alignment","paragraph.spacing.after"];
 public static MutationPlan Create(string documentDigest,string authorizationIdentity,IEnumerable<PlanOperation> source){if(string.IsNullOrWhiteSpace(documentDigest)||string.IsNullOrWhiteSpace(authorizationIdentity))throw new ArgumentException("State and authorization are required.");var raw=source.ToList();if(raw.Count==0)throw new ArgumentException("At least one authorized operation required.");if(raw.Any(x=>!Supported.Contains(x.Property)||x.Provenance!="DIRECT"||string.IsNullOrWhiteSpace(x.ExpectedBefore)||string.IsNullOrWhiteSpace(x.DesiredAfter)))throw new ArgumentException("Unsupported or non-direct operation.");var classes=new List<ConflictClass>();var ops=new List<PlanOperation>();foreach(var g in raw.GroupBy(x=>x.TargetProperty,StringComparer.Ordinal).OrderBy(x=>x.Key,StringComparer.Ordinal)){var semantic=g.GroupBy(x=>x.SemanticKey,StringComparer.Ordinal).Select(x=>x.First()).OrderBy(x=>x.SemanticKey,StringComparer.Ordinal).ToList();if(g.Count()>semantic.Count)classes.Add(ConflictClass.DUPLICATE);if(semantic.Select(x=>x.DesiredAfter).Distinct(StringComparer.Ordinal).Count()>1){classes.Add(ConflictClass.CONFLICTING);ops.AddRange(semantic);continue;}classes.Add(ConflictClass.INDEPENDENT);ops.Add(semantic[0]);}ops=ops.OrderBy(x=>x.TargetProperty,StringComparer.Ordinal).ThenBy(x=>x.SemanticKey,StringComparer.Ordinal).ToList();var seed=string.Join("\n",ops.Select(x=>x.SemanticKey));var id=H(string.Join("|","v26-plan",documentDigest,authorizationIdentity,seed));return new(id,documentDigest,authorizationIdentity,ops,classes,classes.Contains(ConflictClass.CONFLICTING));}
 internal static string H(string s)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(s))).ToLowerInvariant()[..32];}
public enum ExecutionStatus{PENDING,EXECUTING,SUCCEEDED,FAILED,REJECTED}public enum JournalDecision{STARTED,ALREADY_EXECUTED,IDEMPOTENCY_CONFLICT,PREVIOUS_FAILED}
public sealed record ExecutionRecord(string ExecutionId,string IdempotencyKey,string SemanticDigest,string PlanId,string RequestId,string AuthorizationIdentity,string InputDigest,ExecutionStatus Status,IReadOnlyList<PlanOperation> Operations,string? OutputDigest=null,string? OutputReference=null,string? Failure=null,DateTimeOffset? UpdatedAt=null);
public sealed record JournalBeginResult(JournalDecision Decision,ExecutionRecord? Record);public sealed class JournalException(string message):Exception(message);
public sealed class FileExecutionJournal{readonly string file;readonly object gate=new();public FileExecutionJournal(string directory){Directory.CreateDirectory(directory);file=Path.Combine(directory,"journal.json");}
 public JournalBeginResult Begin(string key,MutationPlan plan,string requestId,string inputDigest){lock(gate){var all=Load();var semantic=MutationPlan.H(string.Join("|",plan.PlanId,requestId,inputDigest,plan.AuthorizationIdentity));var prior=all.FirstOrDefault(x=>x.IdempotencyKey==key);if(prior is not null){if(prior.SemanticDigest!=semantic)return new(JournalDecision.IDEMPOTENCY_CONFLICT,prior);return prior.Status switch{ExecutionStatus.SUCCEEDED=>new(JournalDecision.ALREADY_EXECUTED,prior),ExecutionStatus.FAILED=>new(JournalDecision.PREVIOUS_FAILED,prior),_=>new(JournalDecision.ALREADY_EXECUTED,prior)};}var id=MutationPlan.H(string.Join("|","execution",key,semantic));var r=new ExecutionRecord(id,key,semantic,plan.PlanId,requestId,plan.AuthorizationIdentity,inputDigest,ExecutionStatus.EXECUTING,plan.Operations,UpdatedAt:DateTimeOffset.UtcNow);all.Add(r);Save(all);return new(JournalDecision.STARTED,r);}}
 public void Succeed(string id,string outputDigest,string outputReference)=>Update(id,x=>x with{Status=ExecutionStatus.SUCCEEDED,OutputDigest=outputDigest,OutputReference=outputReference,UpdatedAt=DateTimeOffset.UtcNow});public void Fail(string id,string reason)=>Update(id,x=>x with{Status=ExecutionStatus.FAILED,Failure=reason,UpdatedAt=DateTimeOffset.UtcNow});public ExecutionRecord? Get(string id)=>Load().FirstOrDefault(x=>x.ExecutionId==id);
 void Update(string id,Func<ExecutionRecord,ExecutionRecord> f){lock(gate){var a=Load();var n=a.FindIndex(x=>x.ExecutionId==id);if(n<0)throw new JournalException("Execution not found.");a[n]=f(a[n]);Save(a);}}
 List<ExecutionRecord> Load(){if(!File.Exists(file))return[];try{return JsonSerializer.Deserialize<List<ExecutionRecord>>(File.ReadAllText(file))??throw new Exception();}catch(Exception e){throw new JournalException("Journal corrupt: "+e.Message);}}
 void Save(List<ExecutionRecord> a){var tmp=file+"."+Guid.NewGuid().ToString("N")+".tmp";try{File.WriteAllText(tmp,JsonSerializer.Serialize(a));File.Move(tmp,file,true);}catch(Exception e){try{File.Delete(tmp);}catch{}throw new JournalException("Journal write failed: "+e.Message);}}
}
''',encoding='utf-8')
print('V26 foundation materialized')
