#!/usr/bin/env python3
from pathlib import Path
import argparse
ROOT=Path(__file__).resolve().parents[1]
TEST=ROOT/'v22-runtime/tests/LegalValidator.Tests/V27StructuralQaTests.cs'
PROD=ROOT/'v22-runtime/src/LegalValidator/Qa/V27StructuralQa.cs'
p=argparse.ArgumentParser();p.add_argument('--tests-only',action='store_true');p.add_argument('--production-only',action='store_true');a=p.parse_args()
TEST_TEXT=r'''using Xunit;using DocumentFormat.OpenXml.Packaging;using W=DocumentFormat.OpenXml.Wordprocessing;using Nd30.LegalValidator.Qa;namespace Nd30.LegalValidator.Tests;
public sealed class V27StructuralQaTests{
 static string Doc(string d,string name,string text="alpha",string align="left",string after="0",bool table=true,bool pageBreak=false){var p=Path.Combine(d,name);using var x=WordprocessingDocument.Create(p,DocumentFormat.OpenXml.WordprocessingDocumentType.Document);var m=x.AddMainDocumentPart();var pp=new W.ParagraphProperties(new W.Justification{Val=align=="center"?W.JustificationValues.Center:W.JustificationValues.Left},new W.SpacingBetweenLines{After=after});var para=new W.Paragraph(pp,new W.Run(new W.Text(text)));if(pageBreak)para.Append(new W.Run(new W.Break{Type=W.BreakValues.Page}));var body=new W.Body(para);if(table)body.Append(new W.Table(new W.TableRow(new W.TableCell(new W.Paragraph(new W.Run(new W.Text("cell")))))));body.Append(new W.SectionProperties(new W.PageSize{Width=12240,Height=15840},new W.PageMargin{Top=1440,Right=1440,Bottom=1440,Left=1440}));m.Document=new W.Document(body);m.Document.Save();return p;}
 [Fact]public void Snapshot_is_deterministic(){using var t=new T();var p=Doc(t.P,"a.docx");var s=new StructuralSnapshotter().Capture(p);Assert.Equal(s.Identity,new StructuralSnapshotter().Capture(p).Identity);}
 [Fact]public void Allowed_alignment_from_plan_passes(){using var t=new T();var a=Doc(t.P,"a.docx");var b=Doc(t.P,"b.docx",align:"center");var plan=StructuralAuthorityPlan.ForTests("body/p[1]","paragraph.alignment","LEFT","CENTER");Assert.Equal(StructuralQaVerdict.PASS,new StructuralQaService().Compare(a,b,plan).Verdict);}
 [Fact]public void Allowed_spacing_from_plan_passes(){using var t=new T();var a=Doc(t.P,"a.docx");var b=Doc(t.P,"b.docx",after:"120");var plan=StructuralAuthorityPlan.ForTests("body/p[1]","paragraph.spacing.after","0","120");Assert.Equal(StructuralQaVerdict.PASS,new StructuralQaService().Compare(a,b,plan).Verdict);}
 [Fact]public void Caller_has_no_generic_ignore_authority(){Assert.DoesNotContain(typeof(StructuralQaService).GetMethods(),m=>m.Name=="Compare"&&m.GetParameters().Any(p=>p.Name!.Contains("ignore",StringComparison.OrdinalIgnoreCase)||p.Name.Contains("whitelist",StringComparison.OrdinalIgnoreCase)));}
 [Fact]public void Unrelated_text_fails(){using var t=new T();var a=Doc(t.P,"a.docx");var b=Doc(t.P,"b.docx",text:"changed");Assert.Equal(StructuralQaVerdict.FAIL,new StructuralQaService().Compare(a,b,StructuralAuthorityPlan.NoneForTests()).Verdict);}
 [Fact]public void Removed_table_fails(){using var t=new T();var a=Doc(t.P,"a.docx");var b=Doc(t.P,"b.docx",table:false);Assert.Equal(StructuralQaVerdict.FAIL,new StructuralQaService().Compare(a,b,StructuralAuthorityPlan.NoneForTests()).Verdict);}
 [Fact]public void Unexpected_page_break_fails(){using var t=new T();var a=Doc(t.P,"a.docx");var b=Doc(t.P,"b.docx",pageBreak:true);Assert.Equal(StructuralQaVerdict.FAIL,new StructuralQaService().Compare(a,b,StructuralAuthorityPlan.NoneForTests()).Verdict);}
 sealed class T:IDisposable{public string P{get;}=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));public T()=>Directory.CreateDirectory(P);public void Dispose(){try{Directory.Delete(P,true);}catch{}}}
}'''
PROD_TEXT=r'''using System.Security.Cryptography;using System.Text;using DocumentFormat.OpenXml.Packaging;using W=DocumentFormat.OpenXml.Wordprocessing;
namespace Nd30.LegalValidator.Qa;
public enum StructuralQaVerdict{PASS,FAIL}
public sealed record StructuralAuthorityDelta(string TargetPath,string Property,string ExpectedBefore,string DesiredAfter);
public sealed class StructuralAuthorityPlan{internal IReadOnlyList<StructuralAuthorityDelta> Deltas{get;}private StructuralAuthorityPlan(IReadOnlyList<StructuralAuthorityDelta>d)=>Deltas=d;public static StructuralAuthorityPlan ForTests(string target,string property,string before,string after)=>new([new(target,property,before,after)]);public static StructuralAuthorityPlan NoneForTests()=>new([]);}
public sealed record ParagraphFact(string Path,string Text,string Alignment,string SpacingAfter,bool PageBreak);
public sealed record StructuralSnapshot(string Identity,IReadOnlyList<ParagraphFact> Paragraphs,IReadOnlyList<string> Tables,string SectionFacts,string RelationshipFacts,string MediaFacts,string HeaderFooterFacts,string NumberingFacts,string StyleFacts);
public sealed class StructuralSnapshotter{
 public StructuralSnapshot Capture(string path){using var d=WordprocessingDocument.Open(path,false);var body=d.MainDocumentPart?.Document?.Body??throw new InvalidDataException("Missing body");var ps=body.Elements<W.Paragraph>().Select((p,i)=>new ParagraphFact($"body/p[{i+1}]",p.InnerText,(p.ParagraphProperties?.Justification?.Val?.Value.ToString()??"LEFT").ToUpperInvariant(),p.ParagraphProperties?.SpacingBetweenLines?.After?.Value??"0",p.Descendants<W.Break>().Any(x=>x.Type?.Value==W.BreakValues.Page))).ToList();var ts=body.Elements<W.Table>().Select((t,i)=>$"body/table[{i+1}]|{t.InnerText}").ToList();var sect=string.Join(";",body.Descendants<W.SectionProperties>().Select(s=>s.OuterXml));var rel=string.Join(";",d.MainDocumentPart.Parts.OrderBy(x=>x.RelationshipId).Select(x=>$"{x.RelationshipId}|{x.OpenXmlPart.Uri}|{x.OpenXmlPart.ContentType}"));var media=string.Join(";",d.MainDocumentPart.ImageParts.OrderBy(x=>x.Uri.ToString()).Select(x=>$"{x.Uri}|{x.ContentType}|{Hash(x.GetStream())}"));var hf=string.Join(";",d.MainDocumentPart.HeaderParts.Select(x=>Hash(x.GetStream())).Concat(d.MainDocumentPart.FooterParts.Select(x=>Hash(x.GetStream()))).OrderBy(x=>x));var num=d.MainDocumentPart.NumberingDefinitionsPart is null?"":Hash(d.MainDocumentPart.NumberingDefinitionsPart.GetStream());var sty=d.MainDocumentPart.StyleDefinitionsPart is null?"":Hash(d.MainDocumentPart.StyleDefinitionsPart.GetStream());var seed=string.Join("\n",ps.Select(x=>$"{x.Path}|{x.Text}|{x.Alignment}|{x.SpacingAfter}|{x.PageBreak}"))+'\n'+string.Join("\n",ts)+'\n'+sect+'\n'+rel+'\n'+media+'\n'+hf+'\n'+num+'\n'+sty;return new(Hash(new MemoryStream(Encoding.UTF8.GetBytes(seed))),ps,ts,sect,rel,media,hf,num,sty);}
 static string Hash(Stream s){using(s){return Convert.ToHexString(SHA256.HashData(s)).ToLowerInvariant();}}
}
public sealed record StructuralQaResult(StructuralQaVerdict Verdict,IReadOnlyList<string> Diagnostics);
public sealed class StructuralQaService{
 public StructuralQaResult Compare(string source,string output,StructuralAuthorityPlan plan){var a=new StructuralSnapshotter().Capture(source);var b=new StructuralSnapshotter().Capture(output);var e=new List<string>();if(a.Paragraphs.Count!=b.Paragraphs.Count)e.Add("PARAGRAPH_COUNT");var n=Math.Min(a.Paragraphs.Count,b.Paragraphs.Count);for(int i=0;i<n;i++){var x=a.Paragraphs[i];var y=b.Paragraphs[i];if(x.Text!=y.Text)e.Add($"TEXT:{x.Path}");Check(e,plan,x.Path,"paragraph.alignment",x.Alignment,y.Alignment);Check(e,plan,x.Path,"paragraph.spacing.after",x.SpacingAfter,y.SpacingAfter);if(x.PageBreak!=y.PageBreak)e.Add($"PAGE_BREAK:{x.Path}");}if(!a.Tables.SequenceEqual(b.Tables))e.Add("TABLES");if(a.SectionFacts!=b.SectionFacts)e.Add("SECTIONS");if(a.RelationshipFacts!=b.RelationshipFacts)e.Add("RELATIONSHIPS");if(a.MediaFacts!=b.MediaFacts)e.Add("MEDIA");if(a.HeaderFooterFacts!=b.HeaderFooterFacts)e.Add("HEADER_FOOTER");if(a.NumberingFacts!=b.NumberingFacts)e.Add("NUMBERING");if(a.StyleFacts!=b.StyleFacts)e.Add("STYLES");return new(e.Count==0?StructuralQaVerdict.PASS:StructuralQaVerdict.FAIL,e);}
 static void Check(List<string> e,StructuralAuthorityPlan p,string target,string property,string before,string after){if(before==after)return;var d=p.Deltas.Where(x=>x.TargetPath==target&&x.Property==property).ToList();if(d.Count!=1||d[0].ExpectedBefore!=before||d[0].DesiredAfter!=after)e.Add($"UNAUTHORIZED:{target}:{property}");}
}
'''
if not a.production_only:
 TEST.parent.mkdir(parents=True,exist_ok=True);TEST.write_text(TEST_TEXT,encoding='utf-8')
if not a.tests_only:
 PROD.parent.mkdir(parents=True,exist_ok=True);PROD.write_text(PROD_TEXT,encoding='utf-8')
print('V27 structural materialized', 'tests-only' if a.tests_only else 'production-only' if a.production_only else 'all')
